image: kaedroho/django-base
env:
 - RUNNING_IN_DRONE=yes
script:
 - pip3.4 install mock python-dateutil pytz elasticsearch
 - python3.4 setup.py install
 - python3.4 runtests.py
services:
 - postgres
 - dockerfile/elasticsearch
